service: cloudwatch-demo
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  memorySize: 128
  apiGateway:
    apiKeys:
      - demoKey

functions:
  health:
    handler: index.health
    events:
      - http:
          method: GET
          path: /health
          cors: true
          private: true
      - schedule:
          rate: rate(${env:CRON_RATE})
          enabled: ${env:CRON_ENABLE}
