service: aws-monitoring-cross-account
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
      apiKeys:
        - demoKey

functions:
  health:
    handler: index.health
    events:
      - http:
          method: GET
          path: /health
          cors: true
          private: true

